{
  name: error 'name not set',
  image: error 'image not set',
  namespace: error 'namespace not set',
  pullSecret: [],
  pullPolicy: 'IfNotPresent',
  labels: {
    owner: 'callepuzzle',
  },
  annotations: {
    'argocd.argoproj.io/sync-wave': '50',
  },
  podAnnotations: {},
  tag: 'latest',
  port: error 'port not set',
  portName: 'http',
  requestCpu: '100m',
  requestMemory: 128,
  limitCpu: null,
  limitMemory: self.requestMemory,
  hpaMinReplicas: 1,
  hpaMaxReplicas: self.hpaMinReplicas,
  hpaCpuPercent: 50,
  containersInit: [],
  containerMixin: {},
  deploymentMixin: {},
  serverAlias: error 'serverAlias not set',
  serverAliasPath: '/',
  serverAliasPathType: 'Prefix',
}
