{
  name: error 'name not set',
  image: error 'image not set',
  namespace: error 'namespace not set',
  pullSecret: [],
  pullPolicy: 'IfNotPresent',
  labels: {},
  annotations: {
    'argocd.argoproj.io/sync-wave': '50',
  },
  podAnnotations: {},
  tag: 'latest',
  port: null,
  portName: 'http',
  requestCpu: '100m',
  requestMemory: '128Mi',
  limitCpu: null,
  limitMemory: self.requestMemory,
  hpaMinReplicas: 1,
  hpaMaxReplicas: self.hpaMinReplicas,
  hpaCpuPercent: 50,
  containersInit: [],
  userId: null,
  containerMixin: {},
  deploymentMixin: {},
  serverAlias: null,
  serverAliasPath: '/',
  serverAliasPathType: 'Prefix',
}
