name: "test"

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Grafana Tanka
        uses: unfunco/setup-tanka@1.0.0-alpha.1
        with:
          tanka-version: 0.26.0

      - name: Setup Jsonnet
        uses: kobtea/setup-jsonnet-action@v2

      - name: Install deps
        run: jb install -q

      - name: Install deps for testing
        run: jb install -q
        working-directory: ./test

      - name: Format
        run: tk fmt .

      - name: Lint
        run: tk lint .

      - name: Test argocd app
        run: tk show argocd-app
        working-directory: ./test

      - name: Test example app
        run: tk show svelte-template/
        working-directory: ./test
